models/DeliveryBoy.php
<?php
namespace app\models;

use Yii;

class DeliveryBoy extends \yii\db\ActiveRecord
{

    public static function tableName()
    {
        return 'delivery_boy';
    }

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name', 'phone'], 'string', 'max' => 255],
            [['status', 'phone'], 'safe'],
            [['income'], 'integer'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Nombre',
            'status' => 'Status',
            'income' => 'Ingresos',
            'phone' => 'Teléfono',
        ];
    }
}

controllers/DeliveryBoyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\DeliveryBoy;
use app\models\DeliveryBoySearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * DeliveryBoyController implements the CRUD actions for DeliveryBoy model.
 */
class DeliveryBoyController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all DeliveryBoy models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new DeliveryBoySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single DeliveryBoy model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DeliveryBoy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DeliveryBoy();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing DeliveryBoy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing DeliveryBoy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DeliveryBoy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DeliveryBoy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DeliveryBoy::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/OrderController.php
<?php
namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\OrderSearch;
use app\models\Status;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use yii\data\ActiveDataProvider;
use yii\base\Model;
use yii\helpers\Json;
use kartik\mpdf\Pdf;
use kartik\editable\Editable;
// use dosamigos\editable\Editable;
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionIndextoday()
    {
      $model = new Order;

      $expression = new Expression('NOW()');
      $now = (new \yii\db\Query)->select($expression)->scalar();
      $now = substr($now, 0, 10);
      $searchModel = OrderSearch::find()->andFilterWhere(['like', 'date', $now]);

      $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
      'sort' => [
               'defaultOrder' => [
                   'id' => SORT_DESC,
               ]
            ],]);

      if(Yii::$app->request->post('hasEditable'))
      {
        // $model = $this->findModel($model['id']);
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        // $out = Json::encode(['output'=>'','message'=>'']);
        // $post = [];
        // $values = current($_POST['Order']);
        // $post['Order'] = $posted;
        //
        // $orderId = Yii::$app->request->post('editableKey');
        // $order = Order::findOne($orderId);
        // $keys = unserialize(Yii::$app->request->post('editableKey'));
        // $model = $this->findModel($keys['key1'],$keys['key2']);
        //

        if ($model->load($post))
        {
          $value = $model->status;
          return ['output'=> $value, 'message' => ''];

        }
        else {
          return ['otuput' => '', 'message' => ''];
        }

      }

      return $this->render('indextoday', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
          'now' =>  $now,
          'model' => $model,
      ]);
    }


        public function actionIndexcook()
        {

                  $expression = new Expression('NOW()');
                  $now = (new \yii\db\Query)->select($expression)->scalar();
                  $now = substr($now, 0, 10);
                  $searchModel = OrderSearch::find()->andFilterWhere(['like', 'date', $now])->indexBy('id');

                  $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
                                                          'sort' => [
                                                             'defaultOrder' => [
                                                                  'id' => SORT_DESC,
                                                       ]
                                                    ],
                                                  ]);


              if (Yii::$app->request->post('hasEditable'))
                  {
                    $out = Yii::$app->response;
                    //
                    $out->format = \yii\web\Response::FORMAT_JSON;

                    $keys = (Yii::$app->request->post('editableKey'));
                    // $model = $this->findModel($keys);
                    $model = Order::findOne($keys);
                    $out=Json::encode(['output'=>'','message'=>'']);
                    $values=current($_POST['Order']);
                    if($model->key1){
                      $model->status=$values['status'];
                      $model->save();
                    }
                    // $_id=$_POST['editableKey'];
                    // $orderId = Yii::$app->request->post('editableKey');
                    // $model = $this->findModel($_id);
                    // $post=[];
                    // $response = Yii::$app->response;
                    // $response->format = \yii\web\Response::FORMAT_JSON;
                    // $posted = current($_POST['Order']);
                    // $post['Order']=$posted;
                    // if($model->load($post)){
                    //   $model->save();
                    //   if(isset($posted['status']))
                    //   {
                    //     $output=$model->status;
                    //   }
                    //   $out = Json::encode(['output'=>$output, 'message'=>'']);
                    // }
                  echo $out;
                  return;
                  }

                  return $this->renderAjax('indexcook', [
                      'searchModel' => $searchModel,
                      'dataProvider' => $dataProvider,
                      'now' =>  $now,

                      // 'update' => [
                      //     'class' => \dosamigos\editable\EditableAction::className(),
                      //     'modelClass' => Order::className(),
                      //     'forceCreate' => false
                      // ],

                  ]);

        }

    public function actionView($id)
    {


        return $this->render('view', [
            'model' => $this->findModel($id),

        ]);
    }

    public function actionCreate()
    {
        $model = new Order();



        if ($model->load(Yii::$app->request->post())) {
            // $model->ingredients = implode (", ",$model->ingredients);
            // $model->size = implode (", ",$model->size);
            $model->save();
            if (Yii::$app->request->isAjax) {
               // JSON response is expected in case of successful save
               Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
               return ['success' => true];
           }
           return $this->redirect(['view', 'id' => $model->id]);
        }
        if (Yii::$app->request->isAjax) {
          return $this->renderAjax('create', [
            'model' => $model,
          ]);
        }
        else {
            return $this->render('create', [
                'model' => $model,

            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            // $model->ingredients = implode (", ",$model->ingredients);
            // $model->size = implode (", ",$model->size);
            $model->save();
            return $this->redirect(['order/indextoday', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionReport($id) {
      $model = $this->findModel($id);
        $content = $this->renderPartial('_print', [
            'model' => $model,
        ]);

        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE,
            // A4 paper format
            'format' => Pdf::FORMAT_LETTER,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            'marginLeft' => 150,
            'marginRight' => 10,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}',
             // set mPDF properties on the fly
            'options' => ['title' => 'Piccolinas Pizza'],
             // call mPDF methods on the fly
            'methods' => [
                'SetHeader'=>['Piccolinas Pizza'],
                'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }


    public function actions()
    {
        return [
            'delete-multiple' => [
                'class' => 'mickgeek\actionbar\DeleteMultipleAction',
                'modelClass' => 'app\models\Order',
                'afterDeleteCallback' => function ($action) {
                    Yii::$app->getSession()->setFlash('success', 'The selected users have been deleted successfully.');
                },
            ],
        ];
    }
}

views/delivery-boy/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
?>

<div class="delivery-boy-form">

    <?php $form = ActiveForm::begin(); ?>
    <div class="col-md-5">
    <?= $form->field($model, 'name')->textInput(['maxlength' => true, 'placeholder' => 'Nombre del Repartidor'])->label(false) ?>
</div>
<div class="col-md-5">
<?= $form->field($model, 'phone')->textInput(['maxlength' => true, 'placeholder' => 'Teléfono del Repartidor'])->label(false) ?>
</div>
<div class="col-md-1">

        <?= Html::submitButton($model->isNewRecord ? 'Agregar Repartidor' : 'Actualizar Repartidor', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/delivery-boy/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\DeliveryBoySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="delivery-boy-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/delivery-boy/create.php
<?php

use yii\helpers\Html;

?>
<div class="delivery-boy-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/delivery-boy/index.php
<?php

use yii\helpers\Html;
use kartik\grid\GridView;
// use yii\grid\GridView;
use yii\widgets\Pjax;
use kartik\select2\Select2;
use yii\helpers\Json;
use yii\db\Expression;
use yii\helpers\Url;
use app\models\Order;

?>
<div class="delivery-boy-index">

    <p>
        <?= Html::a('Agregar Repartidor', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>


<?php $gridColumns =  [
    [
      'class' => 'kartik\grid\SerialColumn',
      'contentOptions'=>['class'=>'kartik-sheet-style'],
      'width'=>'36px',
      'header'=>'',
      'headerOptions'=>['class'=>'kartik-sheet-style']
    ],
    [
      'class'=>'kartik\grid\ExpandRowColumn',
      'width'=>'50px',
      'value'=>function ($model, $key, $index, $column) {
          return GridView::ROW_COLLAPSED;
      },
      'detail'=>function ($model, $key, $index, $column) {
          return Yii::$app->controller->renderPartial('_form', ['model'=>$model,
        'rowvalue'=>$column->grid->dataProvider->totalCount - $index + 0]);
      },
      'headerOptions'=>['class'=>'kartik-sheet-style'],
      'expandOneOnly'=>true
    ],
    [
      'attribute'=>'name',
      'vAlign'=>'middle',
      'hAlign'=>'right',
        'width'=>'180px',
      // 'format'=>'time',
      'pageSummary'=>false
    ],


    [
      'class'=>'kartik\grid\CheckboxColumn',
    ],
    [
              'class' => 'kartik\grid\ActionColumn',
              'header'=>false,
              // 'pageSummary' => false,
              'options'=>['style'=>'width:150px;'],
              'buttonOptions'=>['class'=>'btn btn-default'],
              'template'=>'<div class="btn-group btn-group-sm text-center" role="group">
              {view}
              </div>',
              'buttons'=>[
                // 'print'=>function($url,$model){
                //   return Html::a('<i class="glyphicon glyphicon-print"></i>',['order/view'],['class'=>'btn-pdfprint btn btn-default','data-pjax'=>'0']);
                // }
              ]
            ],
]?>
<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns'=>$gridColumns,
            'resizableColumns'=>true,
        'headerRowOptions'=>['class'=>'kartik-sheet-style'],
        'filterRowOptions'=>['class'=>'kartik-sheet-style'],
        'pjax'=>true, // pjax is set to always true for this demo
        'toolbar'=> [
            '{export}',
            '{toggleData}',
        ],
        'bordered'=>true,
        'striped'=>true,
        'condensed'=>true,
        'responsive'=>true,
        'hover'=>true,
        'showPageSummary'=>true,
        'panel'=>[
            'type'=>GridView::TYPE_WARNING,
            'heading'=>'Repartidores',
        ],
        'persistResize'=>true,
        'toggleDataOptions'=>['minCount'=>10],
        'export'=>[
              'fontAwesome'=>true,
              'PDF' => [
                      'options' => [
                      ]
                  ],
              ],
        'exportConfig' => [
              GridView::EXCEL => [
                'label' => 'Guardar en XLS',
                'showHeader' => true,
              ],
              GridView::PDF => [
                'label' => 'Guardar en PDF',
                'showHeader' => true,
                'showCaption' => true,
                'showPageSummary' => true,
                'showFooter' => true,
                 'title' => 'Reporte Piccolinas Pizza',
                'options' => ['title' =>'Reporte Piccolinas Pizza'],
                'config' => ['options' => ['title' =>'Reporte Piccolinas Pizza'],],
                'filename' =>'Reporte Piccolinas Pizza',
              ],
    ]]); ?>
<?php Pjax::end(); ?></div>

views/delivery-boy/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\DeliveryBoy */

// $this->title = 'Update Delivery Boy: ' . $model->name;
// $this->params['breadcrumbs'][] = ['label' => 'Delivery Boys', 'url' => ['index']];
// $this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
// $this->params['breadcrumbs'][] = 'Update';
?>
<div class="delivery-boy-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/delivery-boy/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\DeliveryBoy */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Delivery Boys', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="delivery-boy-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
        ],
    ]) ?>

</div>