models/Order.php
<?php

namespace app\models;

use Yii;

class Order extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'orden';
    }

    public function rules()
    {
        return [
            [['wait', 'time', 'cheese_border', 'date', 'only_date', 'ingredients', 'change', 'status', 'size'], 'safe'],
            [['subtotal', 'count', 'total', 'delivery', 'money', 'quantity'], 'integer'],
            [['phone'], 'string', 'max' => 10],
            [['cheese_border', 'address', 'neighborhood', 'status'], 'string', 'max' => 60],
            [['note'], 'string', 'max' => 255],
            [['ingredients', 'total', 'size', 'subtotal', 'money'], 'required'],
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'Folio',
            'count' => 'Folio',
            'phone' => 'Teléfono',
            'wait' => 'Espera',
            'time' => 'Hora',
            'date' => 'Fecha',
            'address' => 'Dirección',
            'neighborhood' => 'Colonia',
            'cheese_border' => 'Orilla',
            'ingredients' => 'Ingredientes',
            'subtotal' => 'Costo',
            'delivery' => 'Envio',
            'money' => 'Paga con',
            'change' => 'Cambio',
            'quantity' => 'Cantidad',
            'note' => 'Anotaciones',
            'status' => 'Status',
            'total' => 'Total',
            'size' => 'Tamaño',
            'only_date' => 'Fecha',
        ];
    }
}

controllers/DeliveryOrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\DeliveryOrder;
use app\models\DeliveryOrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

class DeliveryOrderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new DeliveryOrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionCreate()
    {
        $model = new DeliveryOrder();

        $searchModel = new DeliveryOrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'dataProvider' => $dataProvider,

            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionComeback($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('comeback', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = DeliveryOrder::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actions()
    {
        return [
            'delete-multiple' => [
                'class' => 'mickgeek\actionbar\DeleteMultipleAction',
                'modelClass' => 'app\models\DeliveryOrder',
                'afterDeleteCallback' => function ($action) {
                    Yii::$app->getSession()->setFlash('success', 'Los envios seleccionados fueron borrados.');
                },
            ],
        ];
    }
}

controllers/OrderController.php
<?php
namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\OrderSearch;
use app\models\Status;

use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Expression;
use yii\data\ActiveDataProvider;
use yii\base\Model;
use yii\helpers\Json;
use kartik\mpdf\Pdf;
use kartik\editable\Editable;
// use dosamigos\editable\Editable;
class OrderController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $searchModel = new OrderSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    public function actionIndextoday()
    {
      $model = new Order;

      $expression = new Expression('NOW()');
      $now = (new \yii\db\Query)->select($expression)->scalar();
      $now = substr($now, 0, 10);
      $searchModel = OrderSearch::find()->andFilterWhere(['like', 'date', $now]);

      $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
      'sort' => [
               'defaultOrder' => [
                   'id' => SORT_DESC,
               ]
            ],]);

      if(Yii::$app->request->post('hasEditable'))
      {
        // $model = $this->findModel($model['id']);
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        // $out = Json::encode(['output'=>'','message'=>'']);
        // $post = [];
        // $values = current($_POST['Order']);
        // $post['Order'] = $posted;
        //
        // $orderId = Yii::$app->request->post('editableKey');
        // $order = Order::findOne($orderId);
        // $keys = unserialize(Yii::$app->request->post('editableKey'));
        // $model = $this->findModel($keys['key1'],$keys['key2']);
        //

        if ($model->load($post))
        {
          $value = $model->status;
          return ['output'=> $value, 'message' => ''];

        }
        else {
          return ['otuput' => '', 'message' => ''];
        }

      }

      return $this->render('indextoday', [
          'searchModel' => $searchModel,
          'dataProvider' => $dataProvider,
          'now' =>  $now,
          'model' => $model,
      ]);
    }


        public function actionIndexcook()
        {

                  $expression = new Expression('NOW()');
                  $now = (new \yii\db\Query)->select($expression)->scalar();
                  $now = substr($now, 0, 10);
                  $searchModel = OrderSearch::find()->andFilterWhere(['like', 'date', $now])->indexBy('id');

                  $dataProvider = new ActiveDataProvider(['query' =>$searchModel,
                                                          'sort' => [
                                                             'defaultOrder' => [
                                                                  'id' => SORT_DESC,
                                                       ]
                                                    ],
                                                  ]);


              if (Yii::$app->request->post('hasEditable'))
                  {
                    $out = Yii::$app->response;
                    //
                    $out->format = \yii\web\Response::FORMAT_JSON;

                    $keys = (Yii::$app->request->post('editableKey'));
                    // $model = $this->findModel($keys);
                    $model = Order::findOne($keys);
                    $out=Json::encode(['output'=>'','message'=>'']);
                    $values=current($_POST['Order']);
                    if($model->key1){
                      $model->status=$values['status'];
                      $model->save();
                    }
                    // $_id=$_POST['editableKey'];
                    // $orderId = Yii::$app->request->post('editableKey');
                    // $model = $this->findModel($_id);
                    // $post=[];
                    // $response = Yii::$app->response;
                    // $response->format = \yii\web\Response::FORMAT_JSON;
                    // $posted = current($_POST['Order']);
                    // $post['Order']=$posted;
                    // if($model->load($post)){
                    //   $model->save();
                    //   if(isset($posted['status']))
                    //   {
                    //     $output=$model->status;
                    //   }
                    //   $out = Json::encode(['output'=>$output, 'message'=>'']);
                    // }
                  echo $out;
                  return;
                  }

                  return $this->renderAjax('indexcook', [
                      'searchModel' => $searchModel,
                      'dataProvider' => $dataProvider,
                      'now' =>  $now,

                      // 'update' => [
                      //     'class' => \dosamigos\editable\EditableAction::className(),
                      //     'modelClass' => Order::className(),
                      //     'forceCreate' => false
                      // ],

                  ]);

        }

    public function actionView($id)
    {


        return $this->render('view', [
            'model' => $this->findModel($id),

        ]);
    }

    public function actionCreate()
    {
        $model = new Order();



        if ($model->load(Yii::$app->request->post())) {
            // $model->ingredients = implode (", ",$model->ingredients);
            // $model->size = implode (", ",$model->size);
            $model->save();
            if (Yii::$app->request->isAjax) {
               // JSON response is expected in case of successful save
               Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
               return ['success' => true];
           }
           return $this->redirect(['view', 'id' => $model->id]);
        }
        if (Yii::$app->request->isAjax) {
          return $this->renderAjax('create', [
            'model' => $model,
          ]);
        }
        else {
            return $this->render('create', [
                'model' => $model,

            ]);
        }
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {
            // $model->ingredients = implode (", ",$model->ingredients);
            // $model->size = implode (", ",$model->size);
            $model->save();
            return $this->redirect(['order/indextoday', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionReport($id) {
      $model = $this->findModel($id);
        $content = $this->renderPartial('_print', [
            'model' => $model,
        ]);

        // setup kartik\mpdf\Pdf component
        $pdf = new Pdf([
            // set to use core fonts only
            'mode' => Pdf::MODE_CORE,
            // A4 paper format
            'format' => Pdf::FORMAT_LETTER,
            // portrait orientation
            'orientation' => Pdf::ORIENT_PORTRAIT,
            // stream to browser inline
            'destination' => Pdf::DEST_BROWSER,
            // your html content input
            'content' => $content,
            'marginLeft' => 150,
            'marginRight' => 10,
            // format content from your own css file if needed or use the
            // enhanced bootstrap css built by Krajee for mPDF formatting
            'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
            // any css to be embedded if required
            'cssInline' => '.kv-heading-1{font-size:18px}',
             // set mPDF properties on the fly
            'options' => ['title' => 'Piccolinas Pizza'],
             // call mPDF methods on the fly
            'methods' => [
                'SetHeader'=>['Piccolinas Pizza'],
                'SetFooter'=>['{PAGENO}'],
            ]
        ]);

        // return the pdf output as per the destination setting
        return $pdf->render();
    }


    public function actions()
    {
        return [
            'delete-multiple' => [
                'class' => 'mickgeek\actionbar\DeleteMultipleAction',
                'modelClass' => 'app\models\Order',
                'afterDeleteCallback' => function ($action) {
                    Yii::$app->getSession()->setFlash('success', 'The selected users have been deleted successfully.');
                },
            ],
        ];
    }
}

views/order/_detail.php
<?php

use yii\helpers\Html;
// use yii\widgets\DetailView;
use kartik\detail\DetailView;
use \kartik\date\DatePicker;
use yii2assets\printthis\PrintThis;
use yii\helpers\ArrayHelper;
use app\models\DeliveryOrder;
use app\models\DeliveryBoy;
// $this->title = 'Orden ' . $model->id;

?>
<div class="order-view">

    <h3 class="pull-right">
      <!-- <?= Html::encode($this->title) ?> -->
    </h3>
<!--
    <?= Html::a('<b>Copiar datos</b>', [ 'order/create',
  'phone' => $model->phone,
  'address' => $model->address,
  'neighborhood' => $model->neighborhood,
  'delivery' => 0,],
  ['class' => 'btn btn-info'])?>

<div class="col-md-2">
  <?= Html::a('<b>Modificar</b>', ['update',
      'id' => $model->id,
      'phone' => $model->phone,
      'address' => $model->address,
      'neighborhood' => $model->neighborhood,
      'delivery' => $model->delivery,
      'size' => $model->size,
      'ingredients' => $model->ingredients,
      'quantity' => $model->quantity,
      'cheese_border' => $model->cheese_border,
      'money' => $model->money,
      'change' => $model->change,
      'subtotal' => $model->subtotal,
      'total' => $model->total,
      'wait' => $model->wait,], ['class' => ' pull-left btn btn-primary']) ?>
    </div>

    <div class="col-md-2">

<?= PrintThis::widget([
  'htmlOptions' => [
    'id' => 'PrintThis',
    'btnClass' => 'btn btn-success',
    'btnId' => 'btnPrintThis',
    'btnText' => '<b>Imprimir</b>',
    'btnIcon' => 'fa fa-print'
  ],
  'options' => [
    'debug' => false,
    'importCSS' => false,
    'importStyle' => false,
    // 'loadCSS' => "path/to/my.css",
    'pageTitle' => "<b>Piccolinas Pizza</b>",
    'removeInline' => false,
    'printDelay' => 333,
    'header' => null,
    'formValues' => false,
  ]
]);
?>
</div>

<div class="col-md-2">

<?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
  'class' => 'btn btn-danger pull-left',
  'data' => [
    'confirm' => 'Seguro de borrar este pedido?',
    'method' => 'post',
  ],
  ]) ?>
</div> -->
<!-- <br>
<br>
<br> -->
<!-- <?= \dixonstarter\pdfprint\Pdfprint::widget([
  'elementClass' => '.btn-pdfprint'
]);?> -->
<!-- <a href="url/test.pdf" class="btn-pdfprint">open</a> -->


<div class="hidden">

<div id="PrintThis">

      <?= DetailView::widget([
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],

          'model' => $model,
          'attributes' => [
            [  'attribute' => 'id',
              'value' => $rowvalue,],
              'phone',
              'wait',
              'time',
              'only_date',
              'address',
              'neighborhood',
              ['attribute' => 'cheese_border',
              'value' => $model->cheese_border == '0' ? '' : 'Con Queso',
              'label' => $model->cheese_border == '0' ? '' : 'Orilla',
            ],
              'size',
              'quantity',
              'ingredients',
              'subtotal',
              'delivery',
              'total',
              'money',
              'change',
              // 'note',
              // 'status',
          ],
      ]) ?>

</div>
</div>
&nbsp;
<table>
  <tr>
    <td>

    <?= DetailView::widget([
        'model' => $model,
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],

        'attributes' => [
          // // [  'attribute' => 'id',
          // //   'value' => $rowvalue,],
          // //   'phone',
            ['attribute' => 'wait',
          ],

          // //   'time',
          //   'only_date',
            'address',
            'neighborhood',
            ['attribute' => 'cheese_border',
            'value' => $model->cheese_border == '0' ? '' : 'Con Queso',
            'label' => $model->cheese_border == '0' ? '' : 'Orilla',
          ],
            'size',
            'quantity',
            'ingredients',
            'subtotal',
            'delivery',
            'total',
            'money',
            'change',
            // 'note',
            // 'status',
        ],
    ]) ?>
  </td>
    <td style="vertical-align:top">
      &nbsp;        &nbsp;

<?php
$existance = DeliveryOrder::findOne(['id_order'=>$model->id]);

?>
<?php if ($existance == false || $existance== null){


  echo Html::a('<b>No Repartida</b>', [ '',
  // 'id_order' => $model->id,
  // 'rowvalue' => $rowvalue,

  ],
  ['class' => 'btn btn-warning', 'disabled' => true]);
}
else {
   if ($existance->delivery_time_back == false || $existance->delivery_time_back == null){
  echo Html::a('<b>No Entregada</b>', [ '',
  'disabled' => true,

    // 'id' => $existance->id,
  // 'rowvalue' => $rowvalue,
  ],
  ['class' => 'btn btn-danger', 'disabled' => true]);
  }
  else
  {
      echo Html::a('<b>Repartida por</b> '.$existance->id_delivery_name, [ '',
      ],
      ['class' => 'btn btn-primary', 'disabled' => true,]);
    }

}
?>
</td>
  </tr>
</table>
    </br>
  </br>

</div>

views/order/_detail_editable.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\DetailView;
use app\models\Order;


$this->title = 'Orden ' . $model->id;
// $this->params['breadcrumbs'][] = ['label' => 'Orders', 'url' => ['index']];
// $this->params['breadcrumbs'][] = $this->title;
?>
<div class="order-view">

    <h3 class="pull-right"><?= Html::encode($this->title) ?></h3>
<br>

</br>
</br>
    <p>
      <?php $form = ActiveForm::begin(); ?>

      <div class="form-group">

        <?= $form->field($model, 'status', ['options' => ['value'=> 'Cocinando'] ])->hiddenInput()->label(false); ?>

        <?= Html::submitButton('<b>Cocinar</b>', ['class' => 'btn btn-success', 'style' => 'width: 320px; border-radius: 10px;']) ?>
      </div>
      <?php ActiveForm::end(); ?>

    </p>


</div>

views/order/_detail_indextoday.php
<?php

use yii\helpers\Html;
// use yii\widgets\DetailView;
use kartik\detail\DetailView;
use \kartik\date\DatePicker;
use yii2assets\printthis\PrintThis;
use yii\helpers\ArrayHelper;
use app\models\DeliveryOrder;
use app\models\DeliveryBoy;
// $this->title = 'Orden ' . $model->id;

?>
<div class="order-view">

    <h3 class="pull-right">
      <!-- <?= Html::encode($this->title) ?> -->
    </h3>
<!--
    <?= Html::a('<b>Copiar datos</b>', [ 'order/create',
  'phone' => $model->phone,
  'address' => $model->address,
  'neighborhood' => $model->neighborhood,
  'delivery' => 0,],
  ['class' => 'btn btn-info'])?>

<div class="col-md-2">
  <?= Html::a('<b>Modificar</b>', ['update',
      'id' => $model->id,
      'phone' => $model->phone,
      'address' => $model->address,
      'neighborhood' => $model->neighborhood,
      'delivery' => $model->delivery,
      'size' => $model->size,
      'ingredients' => $model->ingredients,
      'quantity' => $model->quantity,
      'cheese_border' => $model->cheese_border,
      'money' => $model->money,
      'change' => $model->change,
      'subtotal' => $model->subtotal,
      'total' => $model->total,
      'wait' => $model->wait,], ['class' => ' pull-left btn btn-primary']) ?>
    </div>

    <div class="col-md-2">

<?= PrintThis::widget([
  'htmlOptions' => [
    'id' => 'PrintThis',
    'btnClass' => 'btn btn-success',
    'btnId' => 'btnPrintThis',
    'btnText' => '<b>Imprimir</b>',
    'btnIcon' => 'fa fa-print'
  ],
  'options' => [
    'debug' => false,
    'importCSS' => false,
    'importStyle' => false,
    // 'loadCSS' => "path/to/my.css",
    'pageTitle' => "<b>Piccolinas Pizza</b>",
    'removeInline' => false,
    'printDelay' => 333,
    'header' => null,
    'formValues' => false,
  ]
]);
?>
</div>

<div class="col-md-2">

<?= Html::a('Eliminar', ['delete', 'id' => $model->id], [
  'class' => 'btn btn-danger pull-left',
  'data' => [
    'confirm' => 'Seguro de borrar este pedido?',
    'method' => 'post',
  ],
  ]) ?>
</div> -->
<!-- <br>
<br>
<br> -->
<!-- <?= \dixonstarter\pdfprint\Pdfprint::widget([
  'elementClass' => '.btn-pdfprint'
]);?> -->
<!-- <a href="url/test.pdf" class="btn-pdfprint">open</a> -->


<div class="hidden">

<div id="PrintThis">

      <?= DetailView::widget([
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],

          'model' => $model,
          'attributes' => [
            [  'attribute' => 'id',
              'value' => $rowvalue,],
              'phone',
              'wait',
              'time',
              'only_date',
              'address',
              'neighborhood',
              ['attribute' => 'cheese_border',
              'value' => $model->cheese_border == '0' ? '' : 'Con Queso',
              'label' => $model->cheese_border == '0' ? '' : 'Orilla',
            ],
              'size',
              'quantity',
              'ingredients',
              'subtotal',
              'delivery',
              'total',
              'money',
              'change',
              // 'note',
              // 'status',
          ],
      ]) ?>

</div>
</div>
&nbsp;
<table>
  <tr>
    <td>

    <?= DetailView::widget([
        'model' => $model,
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],

        'attributes' => [
          // // [  'attribute' => 'id',
          // //   'value' => $rowvalue,],
          // //   'phone',
            ['attribute' => 'wait',
          ],

          // //   'time',
          //   'only_date',
            'address',
            'neighborhood',
            ['attribute' => 'cheese_border',
            'value' => $model->cheese_border == '0' ? '' : 'Con Queso',
            'label' => $model->cheese_border == '0' ? '' : 'Orilla',
          ],
            'size',
            'quantity',
            'ingredients',
            'subtotal',
            'delivery',
            'total',
            'money',
            'change',
            // 'note',
            // 'status',
        ],
    ]) ?>
  </td>
    <td style="vertical-align:top">
      &nbsp;        &nbsp;

<?php
$existance = DeliveryOrder::findOne(['id_order'=>$model->id]);

?>
<?php if ($existance == false || $existance== null){


  echo Html::a('<b>Repartir</b>', [ 'delivery-order/create',
  'id_order' => $model->id,
  'rowvalue' => $rowvalue,
  'amount' => $model->delivery,
  ],
  ['class' => 'btn btn-warning']);
}
else {
   if ($existance->delivery_time_back == false || $existance->delivery_time_back == null){
     echo Html::a('<b>Repartida por</b> '.$existance->id_delivery_name, [ '',
     ],
     ['class' => 'btn btn-primary', 'disabled' => true,]);

     echo "</br>";
     echo "</br>";
     ?>
     &nbsp;        &nbsp;
     <?php

     echo Html::a('<b>Registrar Regreso</b>', [ 'delivery-order/comeback',
    'id' => $existance->id,
  // 'rowvalue' => $rowvalue,
  ],
  ['class' => 'btn btn-success']);
  }
  else
  {
    echo Html::a('<b>Entregada</b>', [ '',
    ],
    ['class' => 'btn btn-primary', 'disabled' => true,]);
  }

}
?>
</td>
  </tr>
</table>
    </br>
  </br>

</div>

views/order/view.php
<?php
use yii\helpers\Html;
use yii\widgets\DetailView;
use kartik\editable\Editable;
use yii\helpers\Url;
use kartik\mpdf\Pdf;
use yii\widgets\ActiveForm;
use yii2assets\printthis\PrintThis;
use yii\db\Expression;
use app\models\Order;

use app\models\OrderSearch;


$this->title = 'Orden ' . $model->id;

?>
<div class="order-view">

    <!-- <h3 class="pull-right"><?= Html::encode($this->title) ?></h3> -->
<br>

</br>
</br>
    <p>
      <?= Html::a('<b>Modificar</b>', ['update',
      'id' => $model->id,
      'phone' => $model->phone,
      'address' => $model->address,
      'neighborhood' => $model->neighborhood,
      'delivery' => $model->delivery,
      'size' => $model->size,
      'ingredients' => $model->ingredients,
      'quantity' => $model->quantity,
      'cheese_border' => $model->cheese_border,
      'money' => $model->money,
      'change' => $model->change,
      'subtotal' => $model->subtotal,
      'total' => $model->total,
      'wait' => $model->wait,], ['class' => ' pull-left btn btn-primary']) ?>
        &nbsp;        &nbsp;        &nbsp;        &nbsp;

        <?= Html::a('<b>Eliminar</b>', ['delete', 'id' => $model->id], [
          'class' => 'btn btn-danger pull-right fa fa-trash',
          'data' => [
            'confirm' => 'Seguro de eliminar este pedido?',
            'method' => 'post',
          ],
          ]) ?>

          &nbsp;        &nbsp;        &nbsp;        &nbsp;


          <?= Html::a('<b>Copiar datos</b>',[ 'order/create',
        'phone' => $model->phone,
        'address' => $model->address,
        'neighborhood' => $model->neighborhood,
        'delivery' => 0,],
        ['class' => 'btn btn-info'])?>
        &nbsp;        &nbsp;        &nbsp;        &nbsp;

        <?php $previousUrl = null;?>
        <?php $previousUrl = Url::previous();?>

        <!-- <?= Html::a('<i class="fa fa-file"></i> <b>PDF</b>', ['report', 'id'=>$model->id], [
          'class'=>'btn btn-warning',
          'target'=>'_blank',
          'data-toggle'=>'tooltip',
          'title'=>'El ticket aparecerá en una ventana nueva.'
        ]);
        ?> -->
        &nbsp;        &nbsp;        &nbsp;        &nbsp;
        <?= PrintThis::widget([
        	'htmlOptions' => [
        		'id' => 'PrintThis',
        		'btnClass' => 'btn btn-success',
        		'btnId' => 'btnPrintThis',
        		'btnText' => '<b>Imprimir</b>',
        		'btnIcon' => 'fa fa-print'
        	],
        	'options' => [
        		'debug' => false,
        		'importCSS' => false,
        		'importStyle' => false,
        		// 'loadCSS' => "path/to/my.css",
        		'pageTitle' => "Piccolinas Pizza",
        		'removeInline' => false,
        		'printDelay' => 333,
        		'header' => null,
        		'formValues' => true,
        	]
        ]);
        ?>
        &nbsp;        &nbsp;        &nbsp;        &nbsp;
        &nbsp;        &nbsp;        &nbsp;        &nbsp;



    </p>
  </br>
  </br>


  <div id="PrintThis">

    <?= DetailView::widget([
        'model' => $model,
        'formatter' => ['class' => 'yii\i18n\Formatter','nullDisplay' => ''],

        'attributes' => [
            [
              'attribute' => 'count',
              // 'value' => $count,
            ],
            // 'id',
            'phone',
            [
              'attribute' => 'wait',
                'format'=>['text', 2],

              ],
            'time',
            'only_date',
            'address',
            'neighborhood',
            ['attribute' => 'cheese_border',
            'value' => $model->cheese_border == '0' ? '' : 'Con Queso',
            'label' => $model->cheese_border == '0' ? '' : 'Orilla',
          ],
            'size',
            'quantity',
            'ingredients',
            'subtotal',
            'delivery',
            'total',
            'money',
            'change',
            // 'note',
            // 'status',
        ],
    ]) ?>

</div>
<meta http-equiv="refresh" content="25; URL=/index.php?r=order/indextoday">


</div>